[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_treasury = "3PxEqHbGAWZthkyuJvtTjjwYSQ3HRGJVyk8MbjnZP2mt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/mnt/c/Users/eclip/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
