[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_treasury = "AAJL4DeXnWBNRowWjvpkAgwtAACpz6NfaA1T2p8Hrpy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/t3dkich/.config/solana/id.json"

[scripts]
deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/call-deposit.ts"
withdraw-owner = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/call-withdraw-owner.ts"
getaddress = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/get-address.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana-treasury.ts"
